### PR TITLE
Drop support for Django < 2.2 (incl. Python < 3.5); add Django 3.0

### PR DESCRIPTION
**Pull request by michael-k**
Not sure if tests will pass when running against Django 3.0.  Travis runs only on branch `master`.

Followup of etianen/django-s3-storage#101

### CODE REVIEW

**Comment by etianen** [comment]
Do we need to drop support for Django <2.2? 1.11 is an LTS release and will be supported until April 2020.

**Comment by michael-k** [comment]
> Following the release of Django 3.0, we suggest that third-party app authors drop support for all versions of Django prior to 2.2.

https://docs.djangoproject.com/en/dev/releases/3.0/#third-party-library-support-for-older-version-of-django

It's not necessary to drop support for Django < 2.2, but in roughly a month the only release still supported by Django itself will be 1.11.  While 1.11 is an LTS release, it's not the latest LTS release.  2.2 is availabe for over half a year now and people still on 1.11 can continue to use django-s3-storage v0.12.x.

Continuing to support both Django 1.11 and Python 2.7 would mean some overhead due to Django 3.0 coming without `django.utils.six`.

**Comment by etianen** [comment]
You make a good point. :)

Incidentally, if you want to test locally, you can just export a bunch of environmental variables corresponding to your own AWS account.

https://github.com/etianen/django-s3-storage/blob/master/.travis.yml#L12

**Comment by jpadilla** [comment]
@etianen any planned release to PyPI now that Django 3.0 is officially out? Tested against master in a local project and changes work great 👍

**Comment by etianen** [comment]
Released as v0.11.3!

**Comment by beittenc** [comment]
Shouldn't this be v0.12.6? The most recent I'm seeing is 0.12.5 and it still contains the django.utils.six issues.

**Comment by etianen** [comment]
Oops, wrong mailing list!

I'm updating a bunch of libs for Django 3, and django-s3-storage is next on
the list :)

**Comment by dorukgezici** [comment]
Hey @etianen, just wanted to +1 on waiting the release to PyPI. Good luck on your libraries!

**Comment by etianen** [comment]
Released at 0.13.0. :smile:

**Pull request merged**
