### PR TITLE
Add support for server-side encryption.

### PR DESCRIPTION
**Pull request by aaugustin**

### CODE REVIEW

**Comment by etianen** [comment]
Looks promising!

Could you add some description of what `AWS_S3_ENCRYPT_KEY` is and how it works to the readme docs?

**Comment by aaugustin** [comment]
S3 supports "server-side encryption" which gets you a little bit of extra security by encrypting data at rest.

AWS still has the keys and can decrypt files. This can help meeting regulatory requirements, though.

Enabling this feature is just a matter of passing a flag to boto.

I'm going to test this PR in a project and let you know when I'm confident that it works.

EDIT: heh, you reviewed the PR while I was still writing this. Yes, I'll add documentation.

**Comment by etianen** [comment]
So it's a boolean flag?

I have to say, the server-side encryption in S3 always struck me as completely pointless, given they can decrypt your data whenever they choose, but if it's simple to enable there seems no harm in adding it as an option. :)

**Comment by aaugustin** [comment]
Indeed it doesn't help with most threat models... but it's easier to enable it and say "yes we encrypt data at rest" that to argue :-)

**Comment by aaugustin** [comment]
The more correct solution is to roll our own client-side encryption, but then it can become a much more complicated topic depending on how seriously far we want to take the security of our encryption keys.

**Comment by etianen** [comment]
Sigh... yeah.

After the Snowden leaks I briefly got a bit serious about encryption and pulled a load of stuff onto my own local server. Ended up making life very difficult for myself and broke outgoing email quite regularly, including one memorable time when an entire two weeks work of mail was buffered and then sent in one huge dump to my entire clientbase! And, ultimately, nothing was gained, because everyone else I knew was still on Gmail... :P

**Comment by aaugustin** [comment]
So, as discussed above, I tested this PR in a project and it appears to do the job just fine.

**Comment by aaugustin** [comment]
The Travis CI build seems to have failed because it couldn't install Django. I'm not sure why this happened. It seems unrelated to my changes.

**Comment by etianen** [comment]
Travis has been super-flakey this past week.

Thanks for the pull request!

**Pull request merged**
