### PR TITLE
Option to cache signed S3 urls, in order to improve browser caching

### PR DESCRIPTION
**Pull request by devendralaulkar**
Caching of signed URL's - In order to improve caching on browser. I am writing unit test cases - However, I cannot run existing test cases - Is there a dependency or requirement that I am missing?

### CODE REVIEW

**Comment by etianen** [comment]
Thanks for looking into this!

It occurs to me that a simpler way to leverage browser caching is to simply disable the signed URLs for uploaded media files. This is the approach taken by the static files S3 storage.

https://github.com/etianen/django-s3-storage/blob/master/django_s3_storage/storage.py#L329

This has the effect of making all URLs for uploaded media files lose the query params, as well as increasing the browser caching timeout to 365 days.

At the moment, this functionality isn't exposed in a setting, but that would be easy to add.

Or is there some additional gain to be had by caching the signed URLs that I'm not aware of?

N.B. To run the tests you need to set some environmental variables to enable connecting to an Amazon S3 account.

https://github.com/etianen/django-s3-storage/blob/master/tests/django_s3_storage_test/settings.py#L32

**Comment by etianen** [comment]
As of django-s3-storage 0.9.2, it's now possible to disable querystring auth for uploaded files. This should improve browser caching substantially.

See https://github.com/etianen/django-s3-storage#optimizing-media-file-caching

**Comment by devendralaulkar** [comment]
The use case that I was going for - The uploaded files are private, but they could still be cached on the browser for certain amount of time. Thanks for adding the option though.

**Comment by etianen** [comment]
Aha, I see,

It seems a bit wrong to use a cache like this, since different users will have different amounts of time to download a link. However, I see that you've accounted for this by caching the link for half its validity time.

I guess the other way to handle this would be to store the files using an unguessable uuid. That would be the equivalent of an infinitely long expiry time, coupled with the cache.

I think my issue with this is that the files are only secure if the expiry time is low, and if the expiry time is low, browser caching will be almost useless. So it seems a bit of an odd feature.

**Comment by aaugustin** [comment]
FWIW I also came across the same question some time ago and reached the same conclusion as @etianen -- confidentiality and caching are at odds. It may be best to leave this up to users.

**Pull request closed without merging**
