### PR TITLE
Add setting AWS_S3_HOST to allow for non-AWS hosts.

### PR DESCRIPTION
**Pull request by philippbosch**

### CODE REVIEW

**Comment by etianen** [comment]
Looks good! If you could make the following additions, I'll happily pull!

- [ ] Add a corresponding setting for static files storage.
- [ ] Add both new settings to the documentation README.

**Comment by philippbosch** [comment]
Sure thing. I just pushed a new commit that should cover both things.
Thanks for the quick reply!

**Comment by etianen** [comment]
Thanks! It looks like we also need the AWS_S3_HOST_STATIC setting in conf.py, then it's good to pull. :)

**Comment by heldinz** [comment]
Done!

**Comment by etianen** [comment]
Lovely! Thanks for your help!

**Comment by heldinz** [comment]
Thanks so much! This might be a bit cheeky, but any chance of getting this into a release soon?

**Comment by etianen** [comment]
In anticipation of such cheekiness, it's already done!

https://pypi.python.org/pypi/django-s3-storage/0.9.7

**Comment by heldinz** [comment]
Wow, cheers!! :)

**Pull request merged**
