### PR TITLE
Add support for Django 3.1 and Python 3.9

### PR DESCRIPTION
**Pull request by michael-k**
I have no idea if the tests are passing or failing.  Travis doesn't seem to pick up new PRs: https://travis-ci.org/github/etianen/django-s3-storage/pull_requests

If you're interested I could provide a PR that configures GitHub Actions.

### CODE REVIEW

**Comment by etianen** [comment]
It won't run MRs, because the tests need access to some private AWS API keys to run.

How come you're using Python 3.9-dev? I thought Python 3.9 was released?

**Comment by michael-k** [comment]
> How come you're using Python 3.9-dev? I thought Python 3.9 was released?

It is, but it's not available on Travis CI :(
See eg. https://travis-ci.com/github/michael-k/awacs/jobs/398330653

**Comment by etianen** [comment]
How annoying.

I think I'd rather wait until it's available, as otherwise we're not
*actually* testing against Python 3.9. I'll keep this PR open until that
happens.

**Comment by michael-k** [comment]
Python 3.9.0 final is now available on Travis CI. :)  I've updated the PR.

**Comment by etianen** [comment]
Yay!

Still seems to be some references to 3.9-dev in the Travis file. Also, you appear to be referencing the unreleased Django 3.2...?

**Comment by michael-k** [comment]
> some references to 3.9-dev

Right, I've missed the excludes.  Fixed

> referencing the unreleased Django 3.2

3.2 is only used as an upper bound for 3.1, as in `DJANGO='>=3.1,<3.2'`

**Comment by etianen** [comment]
Duh. Need more coffee. :P

Thanks!

**Pull request merged**
