### PR TITLE
Fixed the way exists() works so remove false positives.

### PR DESCRIPTION
**Pull request by kencochrane**
This PR fixes: issue #55 it fixes the exists() method so it handles directories and whether or not files exists in s3, without false positives.

Signed-off-by: Ken Cochrane <kencochrane@gmail.com>

### CODE REVIEW

**Comment by etianen** [comment]
I've adapted your method to something a little more concise using the existing `meta` method. Let me know if it works for you.

5d9cb7390c2114e4b1c0a12c56a7c5ca90959541

**Comment by kencochrane** [comment]
@etianen looks good to me, thanks.

**Comment by etianen** [comment]
Cool. If you could confirm that the master branch is doing what you want,
I'll have a release out soon.

**Comment by kencochrane** [comment]
@etianen I tried master, and it didn't work, I still have the same issue as reported in #55

**Comment by etianen** [comment]
My apologies. I've now added a failing test case that reproduces your issue, and another update that fixes it. Please try again.

**Comment by kencochrane** [comment]
@etianen That worked much better, thank you.

**Comment by etianen** [comment]
v0.11.3 is now out.

**Pull request closed without merging**
