### PR TITLE
switching to upload_fileobj

### PR DESCRIPTION
**Pull request by bramverhelst**
## Why is the change needed?
see https://github.com/etianen/django-s3-storage/issues/133

## Documentation
https://boto3.amazonaws.com/v1/documentation/api/latest/guide/s3-uploading-files.html

## Testing
My current AWS setup/config makes it difficult for me to run the test suite associated with this repo (I use roles/profiles instead of an access key/secret access key combo). @etianen, could you perhaps run the test suite? I assume you're more accustomed with it than I am :smile

### CODE REVIEW

**Comment by etianen** [comment]
This looks excellent. I need to get this repo set up with Github actions, really. But time... time...!

**Comment by etianen** [comment]
Thanks! All tests pass, and I've added GHA integration on master too. :)

Release incoming!

**Comment by bramverhelst** [comment]
@etianen, super! thanks a lot! Looking forward to the release :)

**Comment by etianen** [comment]
It's out now (0.13.5)

**Pull request merged**
